import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");
const repoRoot = path.resolve(root, "..");

const templatePath = path.join(root, "src", "ajax-security-dashboard.template.js");
const outputPath = path.join(root, "dist", "ajax-security-dashboard.js");
const preferredCatalogPath = path.join(repoRoot, "bridge", "data", "devices.json");
const fallbackCatalogPath = path.join(repoRoot, "bridge", "devices.example.json");
const catalogPath = fs.existsSync(preferredCatalogPath) ? preferredCatalogPath : fallbackCatalogPath;

const template = fs.readFileSync(templatePath, "utf8");
const catalog = repairCatalog(JSON.parse(fs.readFileSync(catalogPath, "utf8")));

const generated = `/* eslint-disable */
/* This file is generated by ha-cards/tools/build.mjs. */
\n${template.replace("__DEVICE_CATALOG__", JSON.stringify(catalog, null, 2))}`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, generated);

console.log(`Built ${path.relative(repoRoot, outputPath)} from ${path.relative(repoRoot, catalogPath)}`);

function repairCatalog(value) {
  if (Array.isArray(value)) {
    return value.map(repairCatalog);
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, entryValue]) => [key, repairCatalog(entryValue)]));
  }
  if (typeof value === "string") {
    return repairMojibake(value);
  }
  return value;
}

function repairMojibake(value) {
  if (!isLikelyMojibake(value)) {
    return value;
  }

  const bytes = [];
  for (const char of value) {
    const byte = encodeCp1251Char(char);
    if (byte === null) {
      return value;
    }
    bytes.push(byte);
  }

  return Buffer.from(bytes).toString("utf8");
}

function isLikelyMojibake(value) {
  const matches = value.match(/[РС]/g) || [];
  return matches.length >= 2 && matches.length / value.length > 0.2;
}

function encodeCp1251Char(char) {
  const code = char.codePointAt(0);

  if (code <= 0x7f) {
    return code;
  }
  if (code >= 0x0410 && code <= 0x044f) {
    return code - 0x350;
  }

  const extra = {
    0x0402: 0x80,
    0x0403: 0x81,
    0x201a: 0x82,
    0x0453: 0x83,
    0x201e: 0x84,
    0x2026: 0x85,
    0x2020: 0x86,
    0x2021: 0x87,
    0x20ac: 0x88,
    0x2030: 0x89,
    0x0409: 0x8a,
    0x2039: 0x8b,
    0x040a: 0x8c,
    0x040c: 0x8d,
    0x040b: 0x8e,
    0x040f: 0x8f,
    0x0452: 0x90,
    0x2018: 0x91,
    0x2019: 0x92,
    0x201c: 0x93,
    0x201d: 0x94,
    0x2022: 0x95,
    0x2013: 0x96,
    0x2014: 0x97,
    0x2122: 0x99,
    0x0459: 0x9a,
    0x203a: 0x9b,
    0x045a: 0x9c,
    0x045c: 0x9d,
    0x045b: 0x9e,
    0x045f: 0x9f,
    0x040e: 0xa1,
    0x045e: 0xa2,
    0x0408: 0xa3,
    0x00a4: 0xa4,
    0x0401: 0xa8,
    0x00a9: 0xa9,
    0x0451: 0xb8,
    0x0404: 0xaa,
    0x00ab: 0xab,
    0x00ac: 0xac,
    0x0454: 0xba,
    0x00ae: 0xae,
    0x0407: 0xaf,
    0x00b0: 0xb0,
    0x00b1: 0xb1,
    0x0457: 0xbf,
    0x0406: 0xb2,
    0x0456: 0xb3,
    0x0490: 0xa5,
    0x0491: 0xb4,
    0x00b5: 0xb5,
    0x00b6: 0xb6,
    0x00b7: 0xb7,
    0x2116: 0xb9,
    0x00bb: 0xbb,
    0x0458: 0xbc,
    0x0405: 0xbd,
    0x0455: 0xbe,
    0x00a0: 0xa0,
    0x00a6: 0xa6,
    0x00a7: 0xa7,
    0x00ad: 0xad
  };

  return extra[code] ?? null;
}
